#!/bin/bash
###############################################################################
#
# mailwithtor
# -----------
# A simple socat script to start a local socks server to connect msmtp and Tor.
#
# @author Isis Agora Lovecruft, 0x2cdb8b35
# @date 13 May 2012
# @version 0.0.1
#______________________________________________________________________________
# Changelog:
###############################################################################

SOCKSPORT=9050
SOCAT_LISTEN_PORT=2525
MSMTP_ACCOUNT="default"
MAILSERVER_FQDN="mailserver.com"
MAILSERVER_PORT=465
LOG_FILE="socat-msmtp.log"
LOCK_FILE="socat-msmtp-lockfile"

## If you're calling this from commandline before starting mutt, uncomment the
## following line and use "$ mailwithtor &":

sudo socat -d -d -d -lu -L $HOME/.mailrc/$LOCK_FILE -lf $HOME/.mailrc/$LOG_FILE TCP4-LISTEN:2525,fork SOCKS4A:localhost:$MAILSERVER_FQDN:$MAILSERVER_PORT,socksport=$SOCKSPORT,socksuser=""

## If you're setting "set sendmail='$HOME/scripts/mailwithtor'", then 
## uncomment the following lines: 
## NOTE: this is broken. specifically the getting-the-passphrase-from-the-sudo-
## prompt part.
#sudo %?p?--passphrase-fd 0? socat -d -d -d -lu -L $HOME/.mailrc/$LOCK_FILE -lf $HOME/.mailrc/$LOG_FILE TCP4-LISTEN:2525,fork SOCKS4A:localhost:$MAILSERVER_FQDN:$MAILSERVER_PORT,socksport=$SOCKSPORT,socksuser="" & /usr/bin/msmtp -a $MSMTP_ACCOUNT
#/usr/bin/msmtp -a default $1 $2 $3 $4 $5 $6 $7 $8

