#!/bin/bash
###############################################################################
#
# boilerplate.sh
# --------------
# A simple utility to copy a file to a new location with a new name, and then
# immediately start editing it. For boilerplates.
#
# @author Isis Agora Lovecruft, 0x2cdb8b35
# @date 16 May 2012
# @version 0.0.1
#______________________________________________________________________________
# Changelog:
###############################################################################

#!/bin/bash
#
# pop-up calendar for dzen
#
# based on (c) 2007, by Robert Manea
# http://dzen.geekmode.org/dwiki/doku.php?id=dzen:calendar
# modified by urukrama
# 

TODAY=$(expr `/home/isis/scripts/utcdammit -d | cut -d "/" -f 1` + 0)
MONTH=$(expr `/home/isis/scripts/utcdammit -d | cut -d "/" -f 2` + 0)
YEAR=`date +'%Y'`

(echo '^bg(#000000)^fg(#F2EDD7)'`/home/isis/scripts/utcdammit -c`; echo
\
# current month, hilight header and today
cal \
    | sed -re "s/^(.*[A-Za-z][A-Za-z]*.*)$/^fg(#B23308)^bg(#000000)\1/;s/(^|[ ])($TODAY)($|[ ])/\1^bg(#B23308)^fg(#000000)\2^fg(#F2EDD7)^bg(#000000)\3/"

# next month, hilight header
#[ $MONTH -eq 12 ] && YEAR=`expr $YEAR + 1`
#cal `expr \( $MONTH + 1 \) % 12` $YEAR \
#    | sed -e 's/^\(.*[A-Za-z][A-Za-z]*.*\)$/^fg(#B23308)^bg(#000000)\1/'

sleep 8
) \
    | dzen2 -fg '#F2EDD7' -bg '#000000' -x 864 -y 18 -w 160 -l 9 -sa c -e 'button3=exit;onstart=uncollapse;'-

#-artwiz-nu-medium-r-normal--11-110-75-75-p-90-iso8859-1